---
- name: Install ZeroTier
  ansible.builtin.import_tasks: install.yml
  when:
    - not skip_install | default(false) | bool

- name: Join ZeroTier network
  ansible.builtin.import_tasks: join-network.yml
  tags:
    - configuration

- name: Setup ZeroTier systemd services
  ansible.builtin.import_tasks: systemd.yml
  tags:
    - configuration

- name: Setup ZeroTier bridge
  ansible.builtin.import_tasks: bridge.yml
  tags:
    - configuration
