---
- name: Enable log2ram
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    name: log2ram

- name: Restart log2ram
  ansible.builtin.systemd_service:
    daemon_reload: true
    state: restarted
    name: log2ram
